image: docker:latest

variables:
  SERVICE_NAME: "microservice-sample"
  PRIVATE_REGISTRY: "reg.dolplay.com"
  PRIVATE_REGISTRY_USER: "ci-runner"
  IMAGE_LIBRARY: "data-group"
  IMAGE_NAME: "$PRIVATE_REGISTRY/$IMAGE_LIBRARY/$SERVICE_NAME"
  SWARM_MANAGER: "192.168.85.102:2375"

before_script:
  - docker info

stages:
  - build
  - push
  - deploy

build_image:
  stage: build
  script:
    - docker build -t "$IMAGE_NAME:${CI_BUILD_REF:0:8}" .
    - docker tag "$IMAGE_NAME:${CI_BUILD_REF:0:8}" "$IMAGE_NAME:latest"
  only:
    - master

push_image:
  stage: push
  script:
    - docker login $PRIVATE_REGISTRY -u$PRIVATE_REGISTRY_USER -p$PRIVATE_REGISTRY_PASSWORD
    - docker push "$IMAGE_NAME:${CI_BUILD_REF:0:8}"
    - docker push "$IMAGE_NAME:latest"
  only:
    - master

deploy-service:
  stage: deploy
  script:
    - docker login $PRIVATE_REGISTRY -u$PRIVATE_REGISTRY_USER -p$PRIVATE_REGISTRY_PASSWORD
    - docker -H $SWARM_MANAGER service rm microservice-py
    - docker -H $SWARM_MANAGER service create --with-registry-auth  --name microservice-py reg.dolplay.com/data-group/microservice-sample:${CI_BUILD_REF:0:8}
  only:
    - master
